export const GET_USERS_REQUESTED = "GET_USERS_REQUESTED";
export const GET_USERS_SUCCESS = "GET_USERS_SUCCESS";
export const GET_USERS_FAILED = "GET_USERS_FAILED";

export const POST_USERS_REQUESTED = "POST_USERS_REQUESTED";
export const POST_USERS_SUCCESS = "POST_USERS_SUCCESS";
export const POST_USERS_FAILED = "POST_USERS_FAILED";

export const DELETE_USERS_REQUESTED = "DELETE_USERS_REQUESTED";
export const DELETE_USERS_SUCCESS = "DELETE_USERS_SUCCESS";
export const DELETE_USERS_FAILED = "DELETE_USERS_FAILED";

export const UPDATE_USERS_REQUESTED = "UPDATE_USERS_REQUESTED";
export const UPDATE_USERS_SUCCESS = "UPDATE_USERS_SUCCESS";
export const UPDATE_USERS_FAILED = "UPDATE_USERS_FAILED";

export const UPDATE_USER_DETAILS = "UPDATE_USER_DETAILS";
export const SHOW_SPINNER = "SHOW_SPINNER";
export const CHANGE_GRID_VIEW = "CHANGE_GRID_VIEW";
export const TOGGLE_DELETE_MODAL = "TOGGLE_DELETE_MODAL";
export const TOGGLE_ADD_USE_MODAL = "TOGGLE_ADD_USE_MODAL";
export const LOGGED_IN_USER = "LOGGED_IN_USER";

// user form
export const ADD_NEW_USER = "ADD_NEW_USER";
export const DELETE_NEW_USER = "DELETE_NEW_USER";
export const UPDATE_NEW_USER = "UPDATE_NEW_USER";
